### ISSUE TITLE
the guide info is empty.

### ISSUE THREAD

**Issue by deathbybandaid** [fHDHR/fHDHR_STIRR#12]
Well I am able to get the channels list but it looks like the guide info is empty. It does download something but there are no descriptions and just says "Unavailable" for everything in the guide.

_Originally posted by @Protektor-Desura in https://github.com/fHDHR/fHDHR_STIRR/issues/7#issuecomment-748596056_

**Comment by deathbybandaid** [comment]
Try adjusting in your config `[stirr]xmltv_offset=`

The default is +0000

**Comment by Protektor-Desura** [comment]
I am still not getting any guide data. Here is my config.

```
[main]
uuid = nmnmtomq
cache_dir = 
servicename = STIRR
reponame = fHDHR_STIRR

[fhdhr]
address = 0.0.0.0
discovery_address = 192.168.50.10
port = 5004
stream_type = direct
tuner_count = 4
friendlyname = fHDHR-STIRR
reporting_firmware_name = fHDHR_STIRR
reporting_manufacturer = BoronDust
reporting_model = fHDHR
reporting_firmware_ver = 20201001
reporting_tuner_type = Antenna
device_auth = fHDHR

[epg]
images = pass
method = origin
update_frequency = 43200

[ffmpeg]
path = ffmpeg
bytes_per_read = 1152000

[vlc]
path = cvlc
bytes_per_read = 1152000

[direct_stream]
chunksize = 1048576

[logging]
level = INFO

[database]
type = sqlite
driver = None

[stirr]
force_best = False
xmltv_offset=-0600

[web_ui]
advanced = True
```

**Comment by deathbybandaid** [comment]
I will look in January when I am off vacation.

**Comment by Protektor-Desura** [comment]
No problem. I am central timezone just so you know why I used "xmltv_offset=-0600"

**Comment by deathbybandaid** [comment]
If you want to poke at their API, and see if there is a parameter to set the timezone to UTC, that would help me a ton

**Comment by deathbybandaid** [comment]
@Protektor-Desura if it helps, from a running instance of fHDHR, go to `ip:port/tools`.

I've added a prettify JSON button there

**Comment by deathbybandaid** [comment]
with more testing, the guide data is is as good as it can be. Some channels have some data. Most don't.
